version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - cs-chat-app-mongo:/bitnami/mongodb
    env_file:
      - docker.env
volumes:
  cs-chat-app-mongo:
