version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - cs-chat-app-mongo:/bitnami/mongodb
    env_file:
      - docker.env
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'cs-chat-app-redis:/bitnami/redis/data'

volumes:
  cs-chat-app-mongo:
  cs-chat-app-redis:
